Repository openshift/local-storage-operator, pull requests merged in 2019-09, with the labels that each got.

#41 Bug 1743494: Add createdAd field
  manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#42 Fix rbac permissions when operator is installed via OperatorSource
  manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#43 manifests/local-storage-operator.package.yaml: standardize channel name
  deploy/crd.yaml
  manifests/4.2/image-references
  manifests/4.2/local-storage-operator.v4.2.0.clusterserviceversion.yaml
  manifests/4.2/local-volumes.crd.yaml
  manifests/local-storage-operator.package.yaml
Labels: approved, lgtm, size/XS

#45 Update docs for local-storage-operator to use OperatorSource
  docs/deploy-with-olm.md
  examples/olm/catalog-create-subscribe.yaml
Labels: approved, do-not-merge/hold, lgtm, size/M

#46 Amend docs to use redhat-local-storage-src
  examples/olm/catalog-create-subscribe.yaml
Labels: approved, lgtm, size/XS

#48 Add manifests for 4.3 version
  HACKING.md
  manifests/4.3/image-references
  manifests/4.3/local-storage-operator.v4.2.0.clusterserviceversion.yaml
  manifests/4.3/local-volumes.crd.yaml
  manifests/art.yaml
  manifests/local-storage-operator.package.yaml
Labels: approved, lgtm, size/L
