Repository openshift/local-storage-operator, pull requests merged in 2019-06, with the labels that each got.

#14 Fix some typos, and clarify docs
  docs/deploy-with-olm.md
Labels: approved, needs-ok-to-test, size/L

#17 Various changes for GA
  .gitignore
  Gopkg.lock
  cmd/local-storage-operator/main.go
  config/config.yaml
  deploy/cr.yaml
  deploy/crd.yaml
  deploy/olm/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
  deploy/olm/local-storage-operator/0.0.8/local-volumes.crd.yaml
  deploy/operator.yaml
  docs/deploy-with-olm.md
  examples/olm/create-cr.yaml
  manifests/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
  manifests/local-storage-operator/0.0.8/local-volumes.crd.yaml
  pkg/apis/local/v1/doc.go
  pkg/apis/local/v1/register.go
  pkg/apis/local/v1/types.go
  pkg/apis/local/v1/zz_generated.deepcopy.go
  pkg/controller/api_updater.go
  pkg/controller/controller.go
  pkg/controller/controller_events.go
  pkg/controller/controller_test.go
  tmp/codegen/update-generated.sh
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/types.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  vendor/k8s.io/client-go/tools/record/doc.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/tools/record/events_cache.go
  vendor/k8s.io/client-go/tools/record/fake.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/doc.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
Labels: approved, lgtm, size/XXL

#18 Remove fields from v1 api
  .gitignore
  pkg/apis/local/v1/types.go
  pkg/apis/local/v1/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/diskmaker/diskconfig.go
  pkg/diskmaker/diskconfig_test.go
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/diskmaker_test.go
Labels: approved, lgtm, size/L

#19 Productionize local-storage-operator
  Dockerfile
  Dockerfile.diskmaker
  Dockerfile.diskmaker.rhel7
  Dockerfile.rhel7
  deploy/README.md
  deploy/cluster_rbac.yaml
  deploy/cr.yaml
  deploy/olm/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
  deploy/olm/local-storage-operator/0.0.8/local-volumes.crd.yaml
  deploy/olm/local-storage-operator/local-storage.package.yaml
  manifests/4.2.0/image-references
  manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml
  manifests/4.2.0/local-volumes.crd.yaml
  manifests/art.yaml
  manifests/local-storage-operator.package.yaml
  manifests/local-storage-operator/local-storage.package.yaml
Labels: approved, lgtm, size/L

#25 Fix makefile docker build and add push
  Makefile
Labels: approved, lgtm, ok-to-test, size/S

#21 fix a bug with symlink creation
  HACKING.md
  examples/olm/catalog-create-subscribe.yaml
  examples/olm/create-cr.yaml
  pkg/diskmaker/diskmaker.go
Labels: approved, do-not-merge/hold, lgtm, size/M
