Repository openshift/local-storage-operator, pull requests merged in 2019-12, with the labels that each got.

#51 Added error if a disk can't be found.
  pkg/diskmaker/diskmaker.go
Labels: approved, lgtm, size/XS

#61 Bug 1770183: Allow operator to be upgraded automatically
  manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#62 Bug 1779545: [4.3] Allow operator to be upgraded automatically when an update is available
  manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#59 Bug 1774278: [4.3] Include Tolerations in the LocalVolume CR.
  docs/deploy-with-olm.md
  pkg/apis/local/v1/types.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  test/e2e/localstorage_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#66 Change package version
  manifests/local-storage-operator.package.yaml
Labels: approved, lgtm, size/XS

#67 Bug 1780625: Fix code for finding new disks
  deploy/crd.yaml
  deploy/rbac.yaml
  pkg/diskmaker/blockdevice.go
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/diskmaker_test.go
  pkg/diskmaker/disktable.go
  pkg/diskmaker/disktable_test.go
  test/e2e/localstorage_test.go
Labels: approved, lgtm, size/L

#68 Updating manifests to include Toleration definitions
  manifests/4.3/local-volumes.crd.yaml
  manifests/4.4/local-volumes.crd.yaml
  pkg/apis/local/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#72 Bug 1782480: Restrict kube version
  manifests/4.2/image-references
  manifests/4.2/local-storage-operator.v4.2.0.clusterserviceversion.yaml
  manifests/4.2/local-volumes.crd.yaml
  manifests/4.3/image-references
  manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.3/local-volumes.crd.yaml
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#75 Bug 1783835: Fix managment state displayName
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
