Repository openshift/local-storage-operator, pull requests merged in 2019-03, with the labels that each got.

#2 Add CSV for OLM
  deploy/olm/local-storage-providers.crd.yaml
  deploy/olm/local-storage.package.yaml
  deploy/olm/local-storage.v0.0.1.clusterserviceversion.yaml
Labels: lgtm, size/L

#6 We need to mount /dev in provisioner pod as well
  pkg/controller/controller.go
Labels: lgtm, size/S

#7 Add make test
  Makefile
  pkg/controller/controller_test.go
  vendor/github.com/openshift/api/build/install.go
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/build/v1/doc.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/legacy.go
  vendor/github.com/openshift/api/build/v1/register.go
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/text/collate/build/builder.go
  vendor/golang.org/x/text/collate/build/colelem.go
  vendor/golang.org/x/text/collate/build/contract.go
  vendor/golang.org/x/text/collate/build/order.go
  vendor/golang.org/x/text/collate/build/table.go
  vendor/golang.org/x/text/collate/build/trie.go
Labels: lgtm, size/XXL

#8 Use hyphen in provisioner daemonset name
  pkg/controller/controller.go
Labels: approved, lgtm, size/XS
