Repository openshift/local-storage-operator, pull requests merged in 2019-04, with the labels that each got.

#9 Add privileged for local-storage admin
  deploy/olm/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
  manifests/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#10 Change location of default images to more official versions
  deploy/olm/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
  manifests/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
  pkg/apis/local/v1alpha1/types.go
Labels: approved, size/XS

#13 add docs for OLM deploy
  README.md
  docs/deploy-with-olm.md
  examples/olm/catalog-create-subscribe.yaml
  examples/olm/create-cr.yaml
Labels: ok-to-test, size/L
