Repository openshift/local-storage-operator, pull requests merged in 2019-07, with the labels that each got.

#26 Update docs to use new device Path
  docs/deploy-with-olm.md
  examples/diskmaker_config.yaml
  examples/olm/create-cr.yaml
  examples/provisioner_config.yaml
Labels: approved, lgtm

#29 Replace logrus with klog
  Gopkg.lock
  cmd/diskmaker/diskmaker.go
  cmd/local-storage-operator/main.go
  pkg/controller/api_updater.go
  pkg/controller/controller.go
  pkg/diskmaker/diskmaker.go
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, lgtm, size/XXL

#28 Move the operator examples to stable channel
  HACKING.md
  examples/olm/catalog-create-subscribe.yaml
  manifests/4.2.0/local-volumes.crd.yaml
Labels: approved, lgtm, size/S

#30 Add validation
  cmd/local-storage-operator/main.go
  deploy/crd.yaml
  manifests/4.2.0/local-volumes.crd.yaml
  pkg/apis/local/v1/types.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, size/L

#31 Add e2e tests
  .gitignore
  Dockerfile
  Dockerfile.diskmaker
  Dockerfile.diskmaker.rhel7
  Dockerfile.rhel7
  Gopkg.lock
  Gopkg.toml
  Makefile
  deploy/cr_block.yaml
  deploy/rbac.yaml
  deploy/sa.yaml
  hack/test-e2e.sh
  pkg/controller/controller.go
  test/e2e/localstorage_test.go
  test/e2e/main_test.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/client.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/context.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/e2eutil/wait_util.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/framework.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/main_entry.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/resource_creator.go
  vendor/k8s.io/apiextensions-apiserver/LICENSE
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/pkg/version/def.bzl
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/tools/record/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
Labels: approved, lgtm, size/XXL

#32 Use default namespace if none available
  hack/test-e2e.sh
Labels: approved, lgtm, size/XS

#34 Add local volume finalizer
  cmd/diskmaker/diskmaker.go
  cmd/local-storage-operator/main.go
  deploy/rbac.yaml
  hack/test-e2e.sh
  manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml
  manifests/4.2.0/local-volumes.crd.yaml
  pkg/common/types.go
  pkg/controller/api_updater.go
  pkg/controller/controller.go
  pkg/controller/controller_events.go
  pkg/controller/controller_test.go
  pkg/diskmaker/api_updater.go
  pkg/diskmaker/diskconfig.go
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/diskmaker_test.go
  pkg/diskmaker/event_reporter.go
  test/e2e/localstorage_test.go
Labels: approved, lgtm, size/XXL

#36 Fix command to create PVC
  docs/deploy-with-olm.md
Labels: approved, lgtm, size/XS

#37 Fix example of local-registry
  examples/olm/catalog-create-subscribe.yaml
Labels: approved, lgtm, size/XS

#38 Fix company name
  examples/olm/catalog-create-subscribe.yaml
Labels: approved, lgtm, size/XS

#39 Fix typo
  HACKING.md
  manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
