Repository openshift/local-storage-operator, pull requests merged in 2020-01, with the labels that each got.

#76 Bug 1783857: Use Local Volume consistently for the CRD.
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.4/local-volumes.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#70 4.2: Bug 1781871: Fix code for finding new disks
  deploy/rbac.yaml
  pkg/diskmaker/blockdevice.go
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/diskmaker_test.go
  pkg/diskmaker/disktable.go
  pkg/diskmaker/disktable_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#78 Bug 1784320: Fix install-mode for local-storage operator
  examples/olm/catalog-create-subscribe.yaml
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#74 [4.2] Bug 1782575: restrict minimum Kube version
  manifests/4.2/local-storage-operator.v4.2.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#81 Bug 1744498: Add version information to local-storage-operator
  Makefile
  cmd/diskmaker/diskmaker.go
  cmd/local-storage-operator/main.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#83 Create package for 4.5
  deploy/crd.yaml
  examples/olm/redhat-src-catalog.yaml
  manifests/4.5/image-references
  manifests/4.5/local-storage-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.5/local-volumes.crd.yaml
  manifests/local-storage-operator.package.yaml
Labels: approved, lgtm, size/M

#84 Bug 1793750: Fix ds force rollout
  pkg/controller/api_updater.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
