Repository openshift/local-storage-operator, pull requests merged in 2020-07, with the labels that each got.

#130 Bug 1840127: Enhanced error message reporting
  pkg/diskmaker/diskmaker.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#118 Bug 1850090: [4.4] Use double quotes for skipRange
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#131 Fix bug: logging the wrong error var
  go.sum
  pkg/diskmaker/diskmaker.go
Labels: approved, lgtm

#133 log eval symlink error if it happens
  pkg/diskmaker/diskmaker.go
Labels: approved, lgtm

#123 Auto discovery of devices
  cmd/diskmaker/discovery.go
  cmd/diskmaker/main.go
  deploy/localvolumediscovery_cr.yaml
  deploy/localvolumediscovery_crd.yaml
  deploy/localvolumediscoveryresult_crd.yaml
  deploy/rbac.yaml
  hack/test-e2e.sh
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.6/local-volume-discoveries.crd.yaml
  manifests/4.6/local-volume-discovery-results.crd.yaml
  pkg/apis/local/v1alpha1/localvolumediscovery_types.go
  pkg/apis/local/v1alpha1/localvolumediscoveryresult_types.go
  pkg/apis/local/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_controllers.go
  pkg/controller/localvolumediscovery/localvolumediscovery_controller.go
  pkg/controller/localvolumediscovery/localvolumediscovery_controller_test.go
  pkg/controller/nodedaemon/daemonset_test.go
  pkg/controller/nodedaemon/daemonsets.go
  pkg/controller/nodedaemon/reconcile.go
  pkg/diskmaker/api_mock.go
  pkg/diskmaker/api_updater.go
  pkg/diskmaker/controllers/lvset/matcher.go
  pkg/diskmaker/controllers/lvset/matcher_test.go
  pkg/diskmaker/controllers/lvset/reconcile.go
  pkg/diskmaker/discovery/discovery.go
  pkg/diskmaker/discovery/discovery_test.go
  pkg/diskmaker/discovery/monitor.go
  pkg/diskmaker/discovery/monitor_test.go
  pkg/diskmaker/discovery/sync_result.go
  pkg/diskmaker/discovery/sync_result_test.go
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/diskmaker_test.go
  pkg/diskmaker/event_reporter.go
  pkg/internal/diskutil.go
  pkg/internal/diskutil_test.go
  test/e2e/localvolume_test.go
  test/e2e/localvolumediscovery_test.go
  test/e2e/main_test.go
Labels: approved, lgtm
