Repository openshift/local-storage-operator, pull requests merged in 2020-04, with the labels that each got.

#102 Bug 1779545: Fix skipRange for 4.3
  manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#106 Add BZ component to OWNERS
  OWNERS
Labels: approved, lgtm

#100 Bug 1781502: Updating LSO to use digest for 4.3
  manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#108 Corrected version to 4.2
  README.md
  docs/deploy-with-olm.md
Labels: approved, lgtm

#109 Bug 1826185: Fix status.conditions type
  manifests/4.5/local-volumes.crd.yaml
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#113 Bug 1826185: Add root type and description
  manifests/4.5/local-volumes.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
