Repository openshift/local-storage-operator, pull requests merged in 2020-11, with the labels that each got.

#179 Bug 1887750: Sync CRD manifests to 4.7 dir
  manifests/4.7/local-volume-discoveries.crd.yaml
  manifests/4.7/local-volume-discovery-results.crd.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#180 Bug 1862430: Separating pv lock aquisition and symlinking from loop to a method
  pkg/diskmaker/diskmaker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#185 Bug 1898839: Fix CRD yaml files
  hack/test-e2e.sh
  manifests/4.7/local-volume-discoveries.crd.yaml
  manifests/4.7/local-volume-discovery-results.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
