Repository openshift/local-storage-operator, pull requests merged in 2020-10, with the labels that each got.

#162 Bug 1884285: Add ppc64le/s390x to operator manifest
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#164 Bug 1884285: Fix CSV layout after previous commit
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#165 Bug 1884285: Do not hardcode GOOS/GOARCH
  Makefile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#163 Bug 1884306: Cleanup code for delaying device provisioning
  pkg/diskmaker/controllers/lvset/add.go
  pkg/diskmaker/controllers/lvset/device_age.go
  pkg/diskmaker/controllers/lvset/device_age_test.go
  pkg/diskmaker/controllers/lvset/reconcile.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#166 Bug 1884285: Do not link with -extldflags "-static"
  Makefile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#161 Bug 1882630: fix stale lsblk output
  pkg/diskmaker/discovery/discovery_test.go
  pkg/diskmaker/discovery/monitor_test.go
  pkg/diskmaker/discovery/sync_result_test.go
  pkg/internal/diskutil.go
  pkg/internal/diskutil_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#171 Add opm resources and fix 4.7 build
  manifests/4.7/image-references
  manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/local-volume-discoveries.crd.yaml
  manifests/4.7/local-volume-discovery-results.crd.yaml
  manifests/4.7/local-volume-sets.crd.yaml
  manifests/4.7/local-volumes.crd.yaml
  manifests/local-storage-operator.package.yaml
  opm-bundle/bundle.Dockerfile
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  opm-bundle/manifests/local-volume-discoveries.crd.yaml
  opm-bundle/manifests/local-volume-discovery-results.crd.yaml
  opm-bundle/manifests/local-volume-sets.crd.yaml
  opm-bundle/manifests/local-volumes.crd.yaml
  opm-bundle/metadata/annotations.yaml
Labels: approved, lgtm

#173 Add BZ subcomponent to OWNERS
  OWNERS
Labels: approved, lgtm

#176 Bug 1887750: Bug 1887751: Don't preserve unknown fields in CRs
  manifests/4.6/local-volume-discoveries.crd.yaml
  manifests/4.6/local-volume-discovery-results.crd.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#175 Document testing using opm command
  HACKING.md
  examples/olm/catalog-create-subscribe.yaml
Labels: approved, lgtm

#174 Bug 1887046: Remove unnecessary events
  pkg/diskmaker/controllers/lvset/reconcile.go
  pkg/diskmaker/diskmaker.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#177 Bug 1886973: Hide the LocalVolumeDiscoveryResult CRD from the UI
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#168 Bug 1885700: fix stale lsblk output
  pkg/diskmaker/discovery/discovery_test.go
  pkg/diskmaker/discovery/monitor_test.go
  pkg/diskmaker/discovery/sync_result_test.go
  pkg/internal/diskutil.go
  pkg/internal/diskutil_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
