Repository openshift/local-storage-operator, pull requests merged in 2020-02, with the labels that each got.

#86 Bug 1798198: We need to keep 4.4 channels for now
  manifests/4.4/image-references
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.4/local-volumes.crd.yaml
  manifests/local-storage-operator.package.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#73 [4.3] Bug 1782574: Restrict minimum kube version
  manifests/4.2/local-storage-operator.v4.2.0.clusterserviceversion.yaml
  manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#85 Bug 1788916: Blocking owner deletion should prevent LocalObject from disappearing
  pkg/controller/controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#89 Bug 1800637: Remove orphan storageclasses
  pkg/controller/controller.go
  pkg/controller/controller_events.go
  test/e2e/localstorage_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#88 Warn about installation on OCP from in-tree docs
  docs/deploy-with-olm.md
Labels: approved, lgtm, size/XS

#90 Bug 1802976: Fix typo
  manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.5/local-storage-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#91 Bug 1803215:Prevent deletion of children objects owned by LocalVolume object
  pkg/controller/controller.go
  pkg/controller/controller_events.go
  test/e2e/localstorage_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
