Repository openshift/local-storage-operator, pull requests merged in 2020-08, with the labels that each got.

#139 Bug 1867066: [Auto-discovery] List BIOS-BOOT and EFI-SYSTEM devices as Unavailable
  pkg/diskmaker/discovery/discovery.go
  pkg/diskmaker/discovery/discovery_test.go
  pkg/internal/diskutil.go
  pkg/internal/diskutil_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#137 Bug 1756096: Included must-gather script and image
  Dockerfile.mustgather
  Dockerfile.mustgather.rhel7
  Makefile
  README.md
  docs/must-gather.md
  must-gather/gather
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#140 Bug 1868365: Remove spec.minDeviceCount from LocalVolumeSet CSV example
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#141 Bug 1862443: Remove permission to modify serviceaccounts
  deploy/rbac.yaml
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#144 Bug 1872599: fix e2e tests for localvolumediscovery
  test/e2e/localvolumediscovery_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#135 Bug 1862607: [Auto discovery]: change device size format to int64
  manifests/4.6/local-volume-discovery-results.crd.yaml
  pkg/apis/local/v1alpha1/localvolumediscoveryresult_types.go
  pkg/apis/local/v1alpha1/zz_generated.deepcopy.go
  pkg/diskmaker/discovery/discovery.go
  pkg/diskmaker/discovery/discovery_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
