Repository openshift/local-storage-operator, pull requests merged in 2020-09, with the labels that each got.

#146 BUG 1874695: fix alm-examples in 4.6 csv file
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#149 Bug 1874048: Prevent creation of duplicate PVs for same device
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/event_reporter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#148 BUG 1875060: show correct local-storage-operator version
  cmd/diskmaker/diskmaker.go
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#151 Bug 1876743: Add note about fsType value
  manifests/4.6/local-volumes.crd.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#145 BUG 1869497: fix invalid ownerrefernce for localvolumediscoveryresult CR
  deploy/rbac.yaml
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
  pkg/controller/localvolumediscovery/localvolumediscovery_controller.go
  pkg/controller/localvolumediscovery/localvolumediscovery_controller_test.go
  pkg/diskmaker/discovery/discovery_test.go
  pkg/diskmaker/discovery/sync_result.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#136 Bug 1862610: discover lvm devices in LocalVolumeDiscovery
  pkg/apis/local/v1alpha1/localvolumediscovery_types.go
  pkg/apis/local/v1alpha1/localvolumediscoveryresult_types.go
  pkg/diskmaker/discovery/discovery.go
  pkg/diskmaker/discovery/discovery_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#147 BUG 1872079: change device status to NotAvailable if block mode pv is provisioned on it.
  pkg/controller/localvolumediscovery/localvolumediscovery_controller.go
  pkg/diskmaker/discovery/discovery.go
  pkg/internal/diskutil.go
  pkg/internal/diskutil_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#154 Bug 1881625: Replace goautoneg library
  go.mod
  go.sum
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#160 Bug 1882828: Add discovery result CR to CSV
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#156 Bug 1873424: Bios boot device is provisioned when devicetype is part
  pkg/diskmaker/controllers/lvset/matcher.go
  pkg/diskmaker/controllers/lvset/matcher_test.go
  pkg/diskmaker/discovery/discovery.go
  pkg/diskmaker/discovery/discovery_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#155 Bug 1862489: LSO autoprovisioning should exclude top level disks that are part of LVM volume group
  pkg/common/names.go
  pkg/common/volume_definitions.go
  pkg/controller/localvolumediscovery/localvolumediscovery_controller.go
  pkg/controller/nodedaemon/add.go
  pkg/controller/nodedaemon/daemonsets.go
  pkg/controller/nodedaemon/provisioner_config.go
  pkg/controller/nodedaemon/reconcile.go
  pkg/diskmaker/controllers/lvset/reconcile.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#157 Bug 1862120: LocalVolumeSet should delay provisioning after discovery so it won't race with other provisioners.
  pkg/diskmaker/controllers/lvset/add.go
  pkg/diskmaker/controllers/lvset/device_age.go
  pkg/diskmaker/controllers/lvset/device_age_test.go
  pkg/diskmaker/controllers/lvset/event_reporter.go
  pkg/diskmaker/controllers/lvset/event_reporter_test.go
  pkg/diskmaker/controllers/lvset/reconcile.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#158 Bug 1882775: Prevent creation of duplicate PVs for same device
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/event_reporter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
