Repository openshift/local-storage-operator, pull requests merged in 2021-05, with the labels that each got.

#236 Bug 1959699: Updated gather script to collect pod logs
  must-gather/gather
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#237 Bug 1961120: added permissions to service monitoring
  deploy/rbac.yaml
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#234 Bug 1952820: Add provisioned-by annotation to PV
  pkg/common/provisioner_utils.go
  pkg/common/storage_class_owner.go
  pkg/common/storage_class_owner_test.go
  pkg/controller/localvolume/add.go
  pkg/controller/localvolume/reconcile.go
  pkg/controller/localvolumeset/add.go
  pkg/controller/localvolumeset/reconcile.go
  pkg/controller/localvolumeset/status.go
  pkg/controller/localvolumeset/status_test.go
  pkg/diskmaker/controllers/lv/add.go
  pkg/diskmaker/controllers/lv/create_pv_test.go
  pkg/diskmaker/controllers/lvset/create_pv_test.go
  test/e2e/cleanup_hostdirs.go
  test/e2e/gomega_util.go
  test/e2e/localvolume_test.go
  test/e2e/localvolumeset_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#238 Bug 1959699: Adjusts command used to get pod information
  must-gather/gather
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#235 Bug 1961942: use /disk/by-id name as symlink name
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/diskmaker_test.go
  pkg/diskmaker/event_reporter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#241 Bug 1959699: Use correct namespace for must-gather
  must-gather/gather
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
