Repository openshift/local-storage-operator, pull requests merged in 2021-09, with the labels that each got.

#275 Bug 1994035: increase the polling interval to 1m for lv diskmaker
  diskmaker/controllers/lv/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#274 Bug 1985082: remove hard coded namespace from prometheus rbac rules
  config/manifests/4.9/prometheus-role-binding.yaml
  config/manifests/4.9/prometheus-role.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#278 Bug 2001765: deleter: Don't call reconciler with PVs
  diskmaker/controllers/deleter/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#279 Bug 2001605: Don't block informer threads
  diskmaker/controllers/deleter/reconcile.go
  diskmaker/controllers/lvset/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#267 Bug 2000846: Structure the logs to same format in the entire codebase
  controllers/localvolume/localvolume_controller.go
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/localvolumediscovery/localvolumediscovery_controller_test.go
  controllers/localvolumeset/finalizer.go
  controllers/localvolumeset/localvolumeset_controller.go
  controllers/localvolumeset/localvolumeset_controller_test.go
  controllers/localvolumeset/status.go
  controllers/nodedaemon/reconcile.go
  diskmaker/controllers/deleter/reconcile.go
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lv/reconcile_test.go
  diskmaker/controllers/lvset/create_pv_test.go
  diskmaker/controllers/lvset/device_age_test.go
  diskmaker/controllers/lvset/reconcile.go
  diskmaker/controllers/lvset/reconcile_test.go
  diskmaker_manager/manager.go
  go.mod
  localmetrics/exporter.go
  main.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#271 Bug 2000837: Update RBAC api to v1 from v1beta1 (backport to 4.8)
  deploy/rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#283 Bug 2007522: No new local-storage-operator-metadata-container is buil…
  config/manifests/4.10/image-references
  config/manifests/4.10/local-storage-operator.v4.10.0.clusterserviceversion.yaml
  config/manifests/4.10/local-volume-discoveries.crd.yaml
  config/manifests/4.10/local-volume-discovery-results.crd.yaml
  config/manifests/4.10/local-volume-sets.crd.yaml
  config/manifests/4.10/local-volumes.crd.yaml
  config/manifests/4.10/prometheus-role-binding.yaml
  config/manifests/4.10/prometheus-role.yaml
  config/manifests/local-storage-operator.package.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
