Repository openshift/local-storage-operator, pull requests merged in 2021-04, with the labels that each got.

#225 Add script to sync bundle
  HACKING.md
  Makefile
  hack/sync_bundle
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#227 Bug 1947779: Include maxUnavailable in DaemonSets
  pkg/controller/localvolumediscovery/localvolumediscovery_controller.go
  pkg/controller/nodedaemon/daemonsets.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#226 Add management workload annotations
  deploy/operator.yaml
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  pkg/controller/nodedaemon/daemonsets.go
Labels: approved, bugzilla/valid-bug, lgtm

#231 Bug 1947774: fix imagePullPolicy to ifNotPresent
  deploy/operator.yaml
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  pkg/controller/localvolumediscovery/localvolumediscovery_controller.go
  pkg/controller/nodedaemon/daemonsets.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#228 Bug 1946497: Updates the way lock acquisition throws an error
  pkg/internal/diskutil.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#233 Bug 1954687: Reenabled commented out e2e tests for LocalVolumeDiscovery and LocalVolumeSet
  test/e2e/main_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#230 Rename workload annotations
  deploy/operator.yaml
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  pkg/controller/nodedaemon/daemonsets.go
Labels: approved, bugzilla/valid-bug, lgtm

#229 Bug 1954688: Added example LocalVolumeSet CR
  deploy/localvolumeset_cr.yaml
  deploy/localvolumeset_cr1.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
