Repository openshift/local-storage-operator, pull requests merged in 2021-06, with the labels that each got.

#242 Bug 1966561: add OLM bug workaround for workload partitioning
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#243 Bug 1967444: Add openshift-user-critical priority class
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
  pkg/common/daemonsets_utils.go
  pkg/controller/nodedaemon/daemonsets.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#239 Bug 1963899: Move device information to annotations (backport to 4.7)
  pkg/diskmaker/controllers/lvset/create_pv.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
