Repository openshift/local-storage-operator, pull requests merged in 2021-07, with the labels that each got.

#245 diskmaker: discovery: fix typo in warning message
  diskmaker/discovery/discovery.go
Labels: approved, lgtm

#246 release-4.9-olm-manifests
  config/manifests/4.9/image-references
  config/manifests/4.9/local-storage-operator.v4.9.0.clusterserviceversion.yaml
  config/manifests/4.9/local-volume-discoveries.crd.yaml
  config/manifests/4.9/local-volume-discovery-results.crd.yaml
  config/manifests/4.9/local-volume-sets.crd.yaml
  config/manifests/4.9/local-volumes.crd.yaml
  config/manifests/local-storage-operator.package.yaml
Labels: approved, lgtm

#260 Fix location of MG image
  docs/must-gather.md
Labels: approved, lgtm

#211 Bug 1932714: Remove 4.8 manifests from 4.7 release branch
  manifests/4.8/image-references
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
  manifests/4.8/local-volume-discoveries.crd.yaml
  manifests/4.8/local-volume-discovery-results.crd.yaml
  manifests/4.8/local-volume-sets.crd.yaml
  manifests/4.8/local-volumes.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug

#249 add service and servicemonitor and expose /metrics endpoint for the daemonsets
  assets/templates/localmetrics/service-monitor.yaml
  assets/templates/localmetrics/service.yaml
  common/daemonsets_utils.go
  common/names.go
  common/volume_definitions.go
  config/manager/manager.yaml
  config/manifests/4.9/image-references
  config/manifests/4.9/local-storage-operator.v4.9.0.clusterserviceversion.yaml
  config/manifests/4.9/prometheus-role-binding.yaml
  config/manifests/4.9/prometheus-role.yaml
  config/rbac/monitoring/prometheus_role.yaml
  config/rbac/monitoring/prometheus_role_binding.yaml
  controllers/localvolume/localvolume_controller.go
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/localvolumediscovery/localvolumediscovery_controller_test.go
  controllers/nodedaemon/daemonsets.go
  controllers/nodedaemon/reconcile.go
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lvset/reconcile.go
  diskmaker/discovery/discovery.go
  diskmaker/discovery/sync_result.go
  diskmaker_manager/discovery.go
  diskmaker_manager/manager.go
  examples/olm/catalog-create-subscribe.yaml
  go.mod
  go.sum
  internal/diskutil.go
  internal/diskutil_test.go
  localmetrics/config.go
  localmetrics/exporter.go
  localmetrics/exporter_test.go
  localmetrics/localmetrics.go
  main.go
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  opm-bundle/manifests/prometheus-role-binding.yaml
  opm-bundle/manifests/prometheus-role.yaml
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.mod
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#261 Remove duplicate assets
  .gitignore
  HACKING.md
  hack/sync_bundle
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  opm-bundle/manifests/local-volume-discoveries.crd.yaml
  opm-bundle/manifests/local-volume-discovery-results.crd.yaml
  opm-bundle/manifests/local-volume-sets.crd.yaml
  opm-bundle/manifests/local-volumes.crd.yaml
  opm-bundle/manifests/prometheus-role-binding.yaml
  opm-bundle/manifests/prometheus-role.yaml
Labels: approved, lgtm

#262 remove local provisioner daemonset, no longer used
  assets/templates/local-provisioner-daemonset.yaml
  common/names.go
  config/manager/manager.yaml
  config/manifests/4.9/image-references
  config/manifests/4.9/local-storage-operator.v4.9.0.clusterserviceversion.yaml
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/nodedaemon/daemonset_test.go
  controllers/nodedaemon/daemonsets.go
Labels: approved, lgtm

#264 Fix URL - hyphen vs underscore
  docs/deploy-with-olm.md
Labels: approved, lgtm

#150 Bug 1862429: Ensure that LocalVolumeSet cannot be deleted with released/bound PVCs.
  .gitignore
  common/finalizer_util.go
  common/names.go
  controllers/localvolume/localvolume_controller.go
  controllers/localvolumeset/finalizer.go
  controllers/localvolumeset/finalizer_test.go
  controllers/localvolumeset/localvolumeset_controller.go
  controllers/localvolumeset/localvolumeset_controller_test.go
  controllers/localvolumeset/status_test.go
  test/e2e/aws_disks.go
  test/e2e/cleanup_hostdirs.go
  test/e2e/gomega_util.go
  test/e2e/localvolume_test.go
  test/e2e/localvolumediscovery_test.go
  test/e2e/localvolumeset_test.go
  test/e2e/main_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
