Repository openshift/local-storage-operator, pull requests merged in 2021-12, with the labels that each got.

#301 Bug 2027008: diskmaker-discovery pods don't start because of missing …
  assets/templates/diskmaker-discovery-daemonset.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#303 Bug 2028685: LSO repeatedly reports errors while diskmaker-discovery pod is starting
  HACKING.md
  controllers/localvolumediscovery/localvolumediscovery_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#302 Bug 2026898: Description/details are missing for Local Storage Operator
  config/manifests/4.10/local-storage-operator.clusterserviceversion.yaml
  hack/sync_bundle
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#305 Bug 2033750: Get kube-rbac-proxy from CSV
  assets/templates/diskmaker-discovery-daemonset.yaml
  assets/templates/diskmaker-manager-daemonset.yaml
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/nodedaemon/daemonset_test.go
  controllers/nodedaemon/daemonsets.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
