Repository openshift/local-storage-operator, pull requests merged in 2021-03, with the labels that each got.

#212 Bug 1932816: change package version for 4.8
  deploy/localvolume_crd.yaml
  deploy/localvolumediscovery_crd.yaml
  deploy/localvolumediscoveryresult_crd.yaml
  deploy/localvolumeset_crd.yaml
  manifests/4.6/image-references
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.6/local-volume-discoveries.crd.yaml
  manifests/4.6/local-volume-discovery-results.crd.yaml
  manifests/4.6/local-volume-sets.crd.yaml
  manifests/4.6/local-volumes.crd.yaml
  manifests/4.7/image-references
  manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/local-volume-discoveries.crd.yaml
  manifests/4.7/local-volume-discovery-results.crd.yaml
  manifests/4.7/local-volume-sets.crd.yaml
  manifests/4.7/local-volumes.crd.yaml
  manifests/local-storage-operator.package.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#182 Modify the diskmaker to use internal BlockDevices
  pkg/diskmaker/diskmaker.go
  pkg/diskmaker/diskmaker_test.go
  pkg/diskmaker/disktable.go
  pkg/diskmaker/disktable_test.go
Labels: approved, lgtm, ok-to-test

#214 Bug 1937244: remove leading and trailing whitespaces in lsblk output
  pkg/internal/diskutil.go
  pkg/internal/diskutil_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#217 Updates must-gather Dockerfiles to be more easily built for quay mirroring
  Dockerfile
  Dockerfile.diskmaker
  Dockerfile.mustgather
  Dockerfile.mustgather.rhel7
Labels: approved, lgtm

#218 Bug 1915732: allow users to change allowVolumeExpansion
  pkg/controller/localvolume/resourceapply.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#222 Corrects the WORKDIR of the must-gather image
  Dockerfile.mustgather
  Dockerfile.mustgather.rhel7
Labels: approved, lgtm
