Repository openshift/local-storage-operator, pull requests merged in 2021-11, with the labels that each got.

#290 Bug 2016557: [4.8.z] diskmaker-manager constantly redeployed by LSO …
  pkg/controller/nodedaemon/add.go
  pkg/controller/nodedaemon/aggregate.go
  pkg/controller/nodedaemon/daemonsets.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#268 Bug 1993973 : fix lso_lvset_provisioned_PV_count for multiple lvset
  diskmaker/controllers/lvset/reconcile.go
Labels: lgtm, approved

#291 Bug 2019452: Do not recursively add key/value pairs to logger objects
  controllers/localvolume/localvolume_controller.go
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/localvolumeset/localvolumeset_controller.go
  controllers/nodedaemon/reconcile.go
  diskmaker/controllers/deleter/reconcile.go
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lvset/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#287 Removed OPM bundle for making it easier to consume from CI
  .gitignore
  HACKING.md
  config/bundle.Dockerfile
  config/manifests/4.10/local-storage-operator.clusterserviceversion.yaml
  config/metadata/annotations.yaml
  examples/olm/catalog-create-subscribe.yaml
  hack/sync_bundle
Labels: lgtm, approved

#292 Bug 2010174: Fix duplicate PVs for disk by-names
  diskmaker/controllers/lv/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#295 Update csv filename in art.yaml
  config/manifests/art.yaml
Labels: lgtm, approved

#298 Move static resources into yaml assets
  HACKING.md
  assets/templates/diskmaker-discovery-daemonset.yaml
  assets/templates/diskmaker-manager-daemonset.yaml
  common/daemonsets_utils.go
  common/volume_definitions.go
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/nodedaemon/daemonsets.go
Labels: lgtm, approved
