Repository openshift/local-storage-operator, pull requests merged in 2021-01, with the labels that each got.

#194 Bug 1906519: update crds in 4.7 to use apiextensions.k8s.io/v1
  deploy/localvolume_crd.yaml
  deploy/localvolumediscovery_crd.yaml
  deploy/localvolumediscoveryresult_crd.yaml
  deploy/localvolumeset_crd.yaml
  manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/local-volume-discoveries.crd.yaml
  manifests/4.7/local-volume-discovery-results.crd.yaml
  manifests/4.7/local-volume-sets.crd.yaml
  manifests/4.7/local-volumes.crd.yaml
  opm-bundle/manifests/local-volume-discoveries.crd.yaml
  opm-bundle/manifests/local-volume-discovery-results.crd.yaml
  opm-bundle/manifests/local-volume-sets.crd.yaml
  opm-bundle/manifests/local-volumes.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#199 Bug 1914125: updated localVolume CRD and CSV files examples to encourage using /dev/disk/by-id...
  manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/local-volumes.crd.yaml
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  opm-bundle/manifests/local-volumes.crd.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#198 Bug 1897050: localVolumeSet: keep default MinSize to 1Gi and ignore devices with `boot` substring in the partLabel
  manifests/4.7/local-volume-sets.crd.yaml
  opm-bundle/manifests/local-volume-sets.crd.yaml
  pkg/apis/local/v1alpha1/localvolumediscovery_types.go
  pkg/apis/local/v1alpha1/localvolumeset_types.go
  pkg/diskmaker/controllers/lvset/matcher.go
  pkg/diskmaker/controllers/lvset/matcher_test.go
  pkg/diskmaker/discovery/discovery.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#202 Bug 1917678: Fix no PV being provisioned for missing dev by-id symlink
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
  pkg/diskmaker/controllers/lvset/reconcile.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#192 Bug 1904577: Hide the LocalVolumeDiscoveryResult CRD from the UI
  hack/test-e2e.sh
  manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#203 Bug 1922473: Fix LSO 4.8 ART reconcilliation
  manifests/4.5/local-volumes.crd.yaml
  manifests/4.8/image-references
  manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
  manifests/4.8/local-volume-discoveries.crd.yaml
  manifests/4.8/local-volume-discovery-results.crd.yaml
  manifests/4.8/local-volume-sets.crd.yaml
  manifests/4.8/local-volumes.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
