Repository openshift/local-storage-operator, pull requests merged in 2022-11, with the labels that each got.

#372 Bug 2053505: Remove duplicate/wrong event message when volume is not attached to node
  diskmaker/controllers/lv/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#373 Bump to 4.13
  .ci-operator.yaml
  config/manifests/local-storage-operator.package.yaml
  config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, px-approved, qe-approved, docs-approved

#375 OCPBUGS-396: Add alerts about empty DaemonSet
  assets/templates/localmetrics/prometheus-rule.yaml
  assets/templates/localmetrics/service-monitor.yaml
  assets/templates/localmetrics/service.yaml
  common/names.go
  config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/nodedaemon/reconcile.go
  localmetrics/alerts.go
  localmetrics/exporter.go
  localmetrics/exporter_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug
