Repository openshift/local-storage-operator, pull requests merged in 2022-04, with the labels that each got.

#341 Bug 2067761: Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#340 [release-4.10] Bug 2067702: Remove unused dependencies from go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#343 [release-4.9] Bug 2067701: Remove unused dependencies from go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#346 Bug 2060532: LSO e2e tests are run against default image and namespace
  hack/test-e2e.sh
  test-framework/context.go
  test-framework/context_test.go
  test-framework/framework.go
  test-framework/resource_creator.go
  test-framework/resource_creator_test.go
  test/e2e/aws_disks.go
  test/e2e/cleanup_hostdirs.go
  test/e2e/localvolume_test.go
  test/e2e/localvolumediscovery_test.go
  test/e2e/localvolumeset_test.go
  test/e2e/main_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#347 [release-4.7] Bug 2067699: Update to moby v20.10.14
  go.mod
  go.sum
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#350 Transition LSO manifests to stable channel
  config/bundle.Dockerfile
  config/manifests/art.yaml
  config/manifests/local-storage-operator.package.yaml
  config/manifests/stable/image-references
  config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
  config/manifests/stable/local-volume-discoveries.crd.yaml
  config/manifests/stable/local-volume-discovery-results.crd.yaml
  config/manifests/stable/local-volume-sets.crd.yaml
  config/manifests/stable/local-volumes.crd.yaml
  config/manifests/stable/prometheus-role-binding.yaml
  config/manifests/stable/prometheus-role.yaml
Labels: lgtm, approved

#348 [release-4.6] Bug 2067698: Update to moby v20.10.14
  go.mod
  go.sum
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
