Repository openshift/local-storage-operator, pull requests merged in 2022-07, with the labels that each got.

#361 Bug 2105453: Node reboot causes duplicate volumes
  diskmaker/controllers/lv/fs_interface.go
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lv/reconcile_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#357 Bug 2091873: PVs get stuck in Released after PVC is deleted and Node UID changed
  common/names.go
  diskmaker/controllers/deleter/reconcile.go
  diskmaker/controllers/deleter/reconcile_test.go
  diskmaker/controllers/deleter/testfiles/provisioner_conf.yaml
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lv/reconcile_test.go
  diskmaker/controllers/lvset/reconcile.go
  diskmaker/controllers/lvset/reconcile_test.go
  test-framework/framework.go
  test-framework/utils.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#362 Bug 2104258: Missing PVs after upgrade to 4.8
  pkg/diskmaker/controllers/lv/add.go
  pkg/diskmaker/controllers/lv/fs_interface.go
  pkg/diskmaker/controllers/lv/reconcile.go
  pkg/diskmaker/controllers/lv/reconcile_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#364 Bump CSV and Dockerfile images to 4.12
  Dockerfile
  Dockerfile.diskmaker
  Dockerfile.mustgather.rhel7
  config/manifests/local-storage-operator.package.yaml
  config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, px-approved, qe-approved, docs-approved
