Repository openshift/local-storage-operator, pull requests merged in 2022-02, with the labels that each got.

#299 Bug 2019532: Logger object in LSO does not log source location accurately
  common/provisioner_utils.go
  controllers/localvolume/api_updater.go
  controllers/localvolume/localvolume_controller.go
  controllers/localvolumediscovery/localvolumediscovery_controller.go
  controllers/localvolumediscovery/localvolumediscovery_controller_test.go
  controllers/localvolumeset/finalizer.go
  controllers/localvolumeset/localvolumeset_controller.go
  controllers/localvolumeset/localvolumeset_controller_test.go
  controllers/localvolumeset/status.go
  controllers/nodedaemon/reconcile.go
  diskmaker/api_updater.go
  diskmaker/controllers/deleter/reconcile.go
  diskmaker/controllers/lv/create_pv_test.go
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lv/reconcile_test.go
  diskmaker/controllers/lvset/create_pv_test.go
  diskmaker/controllers/lvset/reconcile.go
  diskmaker/controllers/lvset/reconcile_test.go
  diskmaker/discovery/discovery.go
  diskmaker/discovery/monitor.go
  diskmaker/discovery/sync_result.go
  diskmaker_manager/diskmaker.go
  diskmaker_manager/manager.go
  go.mod
  go.sum
  internal/utils/leaderelection.go
  localmetrics/config.go
  localmetrics/exporter.go
  main.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#310 Bug 2044783: [4.8] bundle CSV alm-examples does not parse
  opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#318 Bug 2012111: Stop enqueing LocalVolumeSet after NotFound error
  controllers/localvolumeset/status.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#320 Bug 2032924: PVs are not being cleaned up after PVC deletion
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#321 2051969: Update OLM metadata to 4.11
  config/manifests/4.11/image-references
  config/manifests/4.11/local-storage-operator.clusterserviceversion.yaml
  config/manifests/4.11/local-volume-discoveries.crd.yaml
  config/manifests/4.11/local-volume-discovery-results.crd.yaml
  config/manifests/4.11/local-volume-sets.crd.yaml
  config/manifests/4.11/local-volumes.crd.yaml
  config/manifests/4.11/prometheus-role-binding.yaml
  config/manifests/4.11/prometheus-role.yaml
  config/manifests/local-storage-operator.package.yaml
Labels: lgtm, approved

#306 Add label for ARM to display local storage operator
  config/manifests/4.11/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#325 Update bundle.Dockerfile to use 4.11 manifests
  config/bundle.Dockerfile
Labels: lgtm, approved

#323 Bug 2052756: [4.10] PVs are not being cleaned up after PVC deletion
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, staff-eng-approved

#326 Bug 2052757: [4.9] PVs are not being cleaned up after PVC deletion
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
