Repository openshift/local-storage-operator, pull requests merged in 2022-12, with the labels that each got.

#374 OCPBUGS-4346: fix naming convention
  config/manifests/art.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low

#378 [release-4.10] OCPBUGS-2477: do not flag PV as cleaned in cache too early
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#377 [release-4.11] OCPBUGS-2476: do not flag PV as cleaned in cache too early
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate
