Repository openshift/local-storage-operator, pull requests merged in 2022-01, with the labels that each got.

#307 Bug 1950827: Updated truncate function to extend length before hashing
  diskmaker/discovery/sync_result.go
  diskmaker/discovery/sync_result_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#308 Bug 2006698: increase the polling interval to 1m for lv diskmaker
  pkg/diskmaker/controllers/lv/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#314 Bug 2041620: bundle CSV alm-examples does not parse
  config/manifests/4.10/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#312 Bug 2041620: bundle CSV alm-examples does not parse
  config/manifests/4.10/local-storage-operator.clusterserviceversion.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#311 Bug 2044782: [4.9] bundle CSV alm-examples does not parse
  config/manifests/4.9/local-storage-operator.v4.9.0.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
