Repository openshift/local-storage-operator, pull requests merged in 2022-03, with the labels that each got.

#329 Bug 2052758: [4.8] PVs are not being cleaned up after PVC deletion
  go.mod
  go.sum
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go
  vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#330 Bug 2059840: Use oc adm inspect to gather everything
  must-gather/gather
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#328 Bug 2052618:Use device location specified by user for LocalVolume PV creation
  Dockerfile
  Dockerfile.diskmaker
  diskmaker/controllers/lv/fs_interface.go
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lv/reconcile_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#332 Bug 2052071: Delete obsolete ServiceMonitor
  controllers/nodedaemon/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#331 Bug 2023614: deleter: Don't call reconciler with PVs
  diskmaker/controllers/deleter/reconcile.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#333 Bug 2061995: Use device location provided by the user
  Dockerfile
  Dockerfile.diskmaker
  diskmaker/controllers/lv/fs_interface.go
  diskmaker/controllers/lv/reconcile.go
  diskmaker/controllers/lv/reconcile_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#334 Bug 2061447: local pv's are in terminating state
  common/provisioner_utils.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#336 Bug 1984785: LSO CSV does not contain disconnected annotation
  config/manifests/4.11/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#338 Remove unused dependencies from go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved
