Repository openshift/local-storage-operator, pull requests merged in 2023-04, with the labels that each got.

#392 bump builder image golang to 1.19
  Dockerfile
Labels: lgtm, approved, px-approved, qe-approved, docs-approved

#401 OCPBUGS-12222: Fix permissions in `examples/olm/catalog-create-subscribe.yaml`
  examples/olm/catalog-create-subscribe.yaml
Labels: lgtm, approved, bugzilla/valid-bug, px-approved, docs-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#395 OCPBUGS-11807: Bump version to 4.14
  config/manifests/local-storage-operator.package.yaml
  config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, px-approved, docs-approved, jira/valid-bug, jira/valid-reference
