Repository openshift/local-storage-operator, pull requests merged in 2025-03, with the labels that each got.

#517 OCPBUGS-51038: fix cleanup storageclass for localvolumeset
  pkg/common/names.go
  pkg/common/resourceapply.go
  pkg/controllers/localvolume/api_updater.go
  pkg/controllers/localvolume/localvolume_controller.go
  pkg/controllers/localvolumeset/api_updater.go
  pkg/controllers/localvolumeset/localvolumeset_controller.go
  pkg/controllers/localvolumeset/localvolumeset_controller_test.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-bug, jira/severity-low, jira/valid-reference

#518 OCPBUGS-51444, OCPBUGS-52105, OCPBUGS-52000: CVE-2025-22868: bump golang.org/x/oauth2 to v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#522 STOR-1880: Role and ClusterRole with too wide permissions
  Makefile
  config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
  config/manifests/stable/local.storage.openshift.io_localvolumediscoveries.yaml
  config/manifests/stable/local.storage.openshift.io_localvolumes.yaml
  config/manifests/stable/local.storage.openshift.io_localvolumesets.yaml
  config/rbac/diskmaker/role.yaml
  config/rbac/role.yaml
  hack/verify-rbac.sh
  pkg/controllers/localvolume/localvolume_controller.go
  pkg/diskmaker/controllers/lv/reconcile.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#523 STOR-1877: Run operators without root user control
  config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference
